# Generated by Django 2.1.7 on 2019-02-24 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0005_auto_20190224_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
