# Generated by Django 2.1.7 on 2019-02-13 15:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('published_date', models.DateField(default=django.utils.timezone.now)),
                ('author', models.CharField(choices=[(1, 'Deval Sethi'), (2, 'Ujjwal Singh Bhadoria'), (3, 'Shishir Maurya'), (4, 'Arghya Debnath')], default=1, max_length=50)),
            ],
        ),
    ]
