# Generated by Django 2.1.7 on 2019-03-15 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(choices=[('1', 'Deval Sethi'), ('2', 'Ujjwal Singh Bhadoria'), ('3', 'Shishir Maurya'), ('4', 'Arghya Debnath')], default=1, max_length=50),
        ),
    ]
