# Generated by Django 2.1.7 on 2019-03-15 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190315_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(choices=[('Deval Sethi', 'Deval Sethi'), ('Ujjwal Singh Bhadoria', 'Ujjwal Singh Bhadoria'), ('Shishir Maurya', 'Shishir Maurya'), ('Arghya Debnath', 'Arghya Debnath')], default='Deval Sethi', max_length=50),
        ),
    ]
