# Generated by Django 2.1.7 on 2019-02-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='year',
            field=models.CharField(choices=[(1, 'First Year'), (2, 'Second Year'), (3, 'Three Year'), (4, 'Fourth Year'), (5, 'Fifth Year'), (6, 'Passout')], default=1, help_text='Your current year', max_length=20),
        ),
    ]
