# Generated by Django 2.1.7 on 2019-02-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_profile_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='branch',
            field=models.CharField(choices=[('1', 'Computer Science Engineering'), ('2', 'Electronics and Communication Engineering'), ('3', 'Electrical engineering'), ('4', 'Mechanical Engineering'), ('5', 'Information Technology Engineering'), ('6', 'Civil Engineering'), ('7', 'Chemical Engineering'), ('8', 'Aeronautical Engineering'), ('9', 'Agricultural engineering'), ('10', 'Mining engineering'), ('11', 'Biochemical engineering'), ('12', 'Electrical and Instrumentation Engineering'), ('13', 'Metallurgical Engineering')], default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='year',
            field=models.CharField(choices=[('1', 'First Year'), ('2', 'Second Year'), ('3', 'Third Year'), ('4', 'Fourth Year'), ('5', 'Fifth Year'), ('6', 'Passout')], default=1, help_text='Your current year', max_length=20),
        ),
    ]
